// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV227PiUd5Aahn4gH7J_-jd5wSGeBMnUc',
    appId: '1:303855004849:web:c775b4ba04bbdeb0bb4690',
    messagingSenderId: '303855004849',
    projectId: 'unite-5f02e',
    authDomain: 'unite-5f02e.firebaseapp.com',
    storageBucket: 'unite-5f02e.firebasestorage.app',
    measurementId: 'G-GPWP1YGZMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5MsoEDQApAq1xGVzYz3MIR65gF41tU98',
    appId: '1:303855004849:android:2851fd8cb57aa600bb4690',
    messagingSenderId: '303855004849',
    projectId: 'unite-5f02e',
    storageBucket: 'unite-5f02e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCcBfN_cT4u0lLaJZCtifKUg95t13AFo',
    appId: '1:303855004849:ios:2d22298e3ac1333abb4690',
    messagingSenderId: '303855004849',
    projectId: 'unite-5f02e',
    storageBucket: 'unite-5f02e.firebasestorage.app',
    iosBundleId: 'com.example.uniteFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeCcBfN_cT4u0lLaJZCtifKUg95t13AFo',
    appId: '1:303855004849:ios:2d22298e3ac1333abb4690',
    messagingSenderId: '303855004849',
    projectId: 'unite-5f02e',
    storageBucket: 'unite-5f02e.firebasestorage.app',
    iosBundleId: 'com.example.uniteFp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV227PiUd5Aahn4gH7J_-jd5wSGeBMnUc',
    appId: '1:303855004849:web:5bbfd19b06d1a8e7bb4690',
    messagingSenderId: '303855004849',
    projectId: 'unite-5f02e',
    authDomain: 'unite-5f02e.firebaseapp.com',
    storageBucket: 'unite-5f02e.firebasestorage.app',
    measurementId: 'G-Y9CCLJTJ29',
  );
}
